### ISSUE TITLE
Spin this off into an organization

### ISSUE THREAD

**Issue by ghost** [andrewsosa001/allstudents-tech#1]
If you come back to this project, I think you would be best serve setting up a GitHub organization so you can incorporate other projects, using this repo as the gh-pages organization site (assuming that's how you intended it).  It would streamline the process of bringing on outside collaborators or adding new projects under the allstudents-tech umbrella.

**Comment by andrewsosa** [comment]
👍

https://github.com/allstudents/
https://allstudents.github.io/

Those email's don't actually work yet...soon 🤐
